### ISSUE TITLE
How to setup name in Kiwi 

### ISSUE THREAD

**Issue by sensorthai** [cesanta/mongoose-os-docs#25]
I get this mqtt message, How I change name from null to my devices.
{
  "gw" : "kiwi-0E9C20",
  "mac" : "ac:23:3f:24:94:47",
  "name" : null,
  "rssi" : -66,
  "adv" : "0201061aff4c000215fda50693a4e24fb1afcfc6eb0764782500000000c5",
  "scan" : ""
}

**Comment by cpq** [comment]
Please use https://vcon.io
