### ISSUE TITLE
mos build for cc3200 issue

### ISSUE THREAD

**Issue by amitlals** [cesanta/mongoose-os-docs#26]
Hi Team,
When I tried to build platform for cc3200 connected with COM port showing below error. Any idea is it TI Device space issue? or cc3200 is too large to accomodate on sensor

*** Out of space, tried to write 25586 bytes ***
make: *** [/data/fwbuild-volumes/latest/apps/app3/cc3200/build_contexts/build_ctx_133522072/build/objs/spiffs.img] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/app'
Error: exit status 2
/go/src/github.com/mongoose-os/mos/mos/build_local.go:679:
/go/src/github.com/mongoose-os/mos/mos/build_local.go:666:
/go/src/github.com/mongoose-os/mos/mos/build_local.go:431:
/go/src/github.com/mongoose-os/mos/mos/build.go:223:
/go/src/github.com/mongoose-os/mos/mos/build.go:166:
/go/src/github.com/mongoose-os/mos/mos/main.go:196: build failed
Error: /go/src/github.com/mongoose-os/mos/mos/build_remote.go:326: build failed
/go/src/github.com/mongoose-os/mos/mos/build.go:223:
/go/src/github.com/mongoose-os/mos/mos/build.go:166:
/go/src/github.com/mongoose-os/mos/mos/main.go:196: build failed

D:\app3>d:\mos build --platform cc3200

**Comment by topelinux** [comment]
Encounter the same issue on Macos

```bash
       Adding ca.pem: SPIFFS_write failed: -10001
*** Out of space, tried to write 27086 bytes ***
make: *** [/data/fwbuild-volumes/2.15.0/apps/app1/cc3200/build_contexts/build_ctx_662828560/build/objs/spiffs.img] Error 1
/data/fwbuild-volumes/2.15.0/apps/app1/cc3200/build_contexts/build_ctx_662828560/deps/modules/mongoose-os/platforms/cc3200/Makefile.build:238: recipe for target '/data/fwbuild-volumes/2.15.0/apps/app1/cc3200/build_contexts/build_ctx_662828560/build/objs/spiffs.img' failed
make: *** Waiting for unfinished jobs....
```

**Comment by cpq** [comment]
This is a wrong repo for this report.
