### ISSUE TITLE
API [cloudiot.googleapis.com] not enabled on projec

### ISSUE THREAD

**Issue by jorgemontalvao** [cesanta/mongoose-os-docs#29]
For a new project, before create a device registry, you have to enable Google API and billing.

This command does not work for new projects:
gcloud iot registries create iot-registry --region europe-west1 --event-notification-config=topic=iot-topic

Error:
API [cloudiot.googleapis.com] not enabled on project [<project_number>]

**Comment by cpq** [comment]
This is a wrong repo for this report.
